language: generic

os:
  - linux

services:
  - docker

before_install:
  - docker build -t keshavcodex/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keshavcodex/docker-react npm run test
